### ISSUE TITLE
请问一下数据集需要多大硬盘空间

### ISSUE THREAD

**Issue by LYMDLUT** [MasterBin-IIAU/Unicorn#1]
非常感谢您对跟踪领域的重大贡献，由于数据集太大，请问具体需要多大呢？4T能否装下呢?

**Comment by MasterBin-IIAU** [comment]
@LYMDLUT Hi, thanks for your appreciation of our work. 4T is definitely enough for storing all datasets. I think that 2T is also enough. The largest dataset we used is TrackingNet. The complete TrackingNet may consume huge space. However, since we only use 4 of 12 splits, the space needed has been largely reduced.

**Comment by LYMDLUT** [comment]
非常感谢，期待您在各平台的讲解！

**Comment by LYMDLUT** [comment]
期待您更加优秀的工作！

**Comment by MasterBin-IIAU** [comment]
@LYMDLUT Thanks for your appreciation :)
